prompt_1: |
  Based on the following financial statements, assess whether EPS will increase or decrease in the next year:
  {balance_income_sheet}
  
  Solve this problem step by step:
  1. Analyze the Balance Sheet:
     1A. Extract balance sheet data including Year-over-Year percentage changes for each item.
     1B. Analyze the balance sheet data for key insights and trends.
  
  2. Perform a Cash Flow Analysis:
     2A. Analyze liquidity and cash movement based on the balance sheet and income statement trends.
  
  3. Analyze the Income Statement:
     3A. Extract income statement data including Year-over-Year percentage changes for each item.
     3B. Analyze the income statement data for key insights and trends.
  
  4. Financial Ratio Analysis:
     4A. Using the balance sheet and income statement data, calculate key financial ratios for the two most recent periods.
     4B. Analyze the calculated financial ratios for key insights and trends.
  
  5. Final Summary and Future Outlook:
     5A. Based on the balance sheet, income statement, and financial ratio analysis, produce a comprehensive assessment of the company's financial health and future profitability.
  
  6. EPS Prediction for Next Year:
     6A. Assess whether EPS is likely to increase or decrease based on findings.
     6B. First provide the step-wise reasoning. After your reasoning, return the results in the EXACT JSON format specified below. The JSON block, enclosed in ```json and ```, must be the VERY LAST part of your response. Do NOT include any text, comments, or explanations after the closing ``` of the JSON block.
     ```json
   {{
       "direction_of_eps_change": "<Increase/Decrease>",
       "magnitude_of_change": "<Brief description of magnitude, e.g., Slight, Moderate, Significant>",
       "certainty_of_assessment": "<High/Medium/Low>",
       "reason": "<Concise explanation for the prediction. Ensure any newlines within this string are properly escaped as \\n.>"
     }}
   ```
